Added prerequisites for Windows OS
ts-safeql/safeql pull request #256
Opened 2024-08-21 04:46 UTC by Vishal-beep136

Added prerequisites for Windows OS.

2024-09-08 16:01 UTC, karlhorky commented on README.md
> +```bash
````suggestion
### Prerequisites

1. Set up ESLint following [the `typescript-eslint` Getting Started docs](https://typescript-eslint.io/getting-started), to enable ESLint to work on TypeScript code
2. Install [the `node-gyp` prerequisites for your operating system](https://github.com/nodejs/node-gyp#on-unix)

```bash
````

2024-09-08 16:01 UTC, karlhorky commented on docs/guide/getting-started.md
> +
```suggestion
1. Set up ESLint following [the `typescript-eslint` Getting Started docs](https://typescript-eslint.io/getting-started), to enable ESLint to work on TypeScript code
2. Install [the `node-gyp` prerequisites for your operating system](https://github.com/nodejs/node-gyp#on-unix)

```

2024-09-08 16:02 UTC, karlhorky requested changes
Made some comments above - I think that we can probably just link to the `node-gyp` docs, because they contain the cross-platform setup instructions which are needed here

@Newbie012 thoughts?

2024-09-10 07:56 UTC, karlhorky approved these changes
LGTM, thanks!

@Newbie012 over to you for final approval + merge

2024-09-10 08:11 UTC, Newbie012 commented
When I think about it, maybe it would be wise to mention node-gyp only for Windows, since you don't really need to do anything when using Linux/MacOS

2024-09-10 08:40 UTC, karlhorky commented
> you don't really need to do anything when using Linux/MacOS

This is not true - at least not for macOS:

1. [Newer macOS doesn't have Python preinstalled](https://www.freecodecamp.org/news/how-to-fix-python-installation-errors-on-mac/#:~:text=Macs%20no%20longer%20come%20with%20Python%20pre%2Dinstalled.)
2. Xcode Command Line Tools also not pre-installed on macOS

The [`devel` docs section of packages for Ubuntu Noble](https://packages.ubuntu.com/noble/devel/) seem to indicate that GCC and make are preinstalled on Ubuntu.

But I guess macOS and Windows are going to make up the majority of users?

2024-09-10 09:02 UTC, merged